## Joint State Controller ----------------------------------------
# Updates the joint positions
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

## Joint Trajectory Effort Controller ----------------------------------------
rf_trajectory_effort_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - j_coxa_rf
    - j_femur_rf
    - j_tibia_rf

  gains:
    j_coxa_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
## Joint Trajectory Position Controller ----------------------------------------
rf_trajectory_pos_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - j_coxa_rf
    - j_femur_rf
    - j_tibia_rf

  gains:
    j_coxa_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
## Joint Trajectory Velocity Controller ----------------------------------------
rf_trajectory_vel_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - j_coxa_rf
    - j_femur_rf
    - j_tibia_rf
  gains:
    j_coxa_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_rf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}


## Joint Trajectory Effort Controller ----------------------------------------
rr_trajectory_effort_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - j_coxa_rr
    - j_femur_rr
    - j_tibia_rr

  gains:
    j_coxa_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
## Joint Trajectory Position Controller ----------------------------------------
rr_trajectory_pos_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - j_coxa_rr
    - j_femur_rr
    - j_tibia_rr

  gains:
    j_coxa_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
## Joint Trajectory Velocity Controller ----------------------------------------
rr_trajectory_vel_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - j_coxa_rr
    - j_femur_rr
    - j_tibia_rr
  gains:
    j_coxa_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_rr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}


## Joint Trajectory Effort Controller ----------------------------------------
lf_trajectory_effort_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - j_coxa_lf
    - j_femur_lf
    - j_tibia_lf

  gains:
    j_coxa_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
## Joint Trajectory Position Controller ----------------------------------------
lf_trajectory_pos_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - j_coxa_lf
    - j_femur_lf
    - j_tibia_lf

  gains:
    j_coxa_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
## Joint Trajectory Velocity Controller ----------------------------------------
lf_trajectory_vel_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - j_coxa_lf
    - j_femur_lf
    - j_tibia_lf
  gains:
    j_coxa_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_lf: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}



## Joint Trajectory Effort Controller ----------------------------------------
lr_trajectory_effort_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - j_coxa_lr
    - j_femur_lr
    - j_tibia_lr

  gains:
    j_coxa_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
## Joint Trajectory Position Controller ----------------------------------------
lr_trajectory_pos_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - j_coxa_lr
    - j_femur_lr
    - j_tibia_lr

  gains:
    j_coxa_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
## Joint Trajectory Velocity Controller ----------------------------------------
lr_trajectory_vel_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - j_coxa_lr
    - j_femur_lr
    - j_tibia_lr
  gains:
    j_coxa_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_femur_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}
    j_tibia_lr: {p: 1.5,  d: 0, i: 0.002, i_clamp: 0.1}

